[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
# Optimize for Streamlit Cloud deployment
maxUploadSize = 5
enableCORS = false
enableXsrfProtection = true
headless = true
port = 8501

[browser]
gatherUsageStats = false

[global]
# Memory optimization for Streamlit Cloud
maxCachedMessageAge = 2
suppressDeprecationWarnings = true

[logger]
# Reduce logging overhead in production
level = "error"
